export const Html = {
    BASKET : "basket",
    CHANGE_GAME_BUTTON : "changeGameButton", 
    GAME_CHANGE_MODAL : "modalGameChange", //div
    SELECT_GAME : "selectGame", //select
    SELECT_GAME_BUTTON : "selectGameButton",
    QUIT_SELECT_GAME_BUTTON : "quitSelectGameButton",
    QUIT_ADD_PLAYER_BUTTON : "quitAddPlayerButton",
    GAME_NAME_DIV : "gameName",
    //player buttons
    REMOVE_PLAYER_CLASS : "remove",
    MINUS_1_BUTTON : "minus1",
    DOWN_BUTTON : "down",
    UP_BUTTON : "up",
    DROP_IMG_CLASS : "dropImg",
    DROP_NUM_INPUT : "dropNum",
    MINUS_DROP_NUM_BUTTON : "minusM",
    PLAY_BUTTON : "game1",
    TURN_BUTTON : "counting",
    POINT_CLASS: "point",
    ROLE_ICON_CLASS: "role",
    NEXT_BUTTON : "start",
    SHOW_PLAYER_CLASS : "showPlayer",
    CHOOSE_ROLES_OVERLAY : "chooseRolesOverlay",
    CHOOSE_ROLES : "chooseRoles",
    ACTIVE_ROLES : "activeRoles",
    PASSIVE_ROLES : "passiveRoles",
    ROLE_ICON_CHOICE_CLASS : "roleChoice",
    ROLES_SELECTED_BUTTON : "rolesSelectedButton",
    ROLE_ICON : "roleIcon",
    PLAYER_OP_CLASS : "playerOp",
    SHOW_ROLE_WINDOW : "showRoleOverlay",
    SHOW_ROLE_CONTENT: "showRoleContent",
    SHOW_ROLE_IMG : "showRoleImg",
    SHOW_ROLE_NAME : "showRoleName",
    SHOW_ROLE_DESC : "showRoleDesc",
    SHOW_ROLE_ROLE : "showRoleRole",
    SHOW_ROLE_CLOSE_BUTTON : "showRoleCloseButton",
    SHOW_ROLE_ICON : "showPlayerImg",
    CITIZEN_COUNT : "citizenCount",
    FIRST_NIGHT_OVERLAY : "firstNightOverlay",
    FIRST_NIGHT_CONTENT : "firstNightContent",
    FIRST_NIGHT_KILLERS_MEETING : "firstNightKillersMeeting",
    FIRST_NIGHT_CHAMELEON : "firstNightChameleon",
    FIRST_NIGHT_DIRECTOR : "firstNightDirector",
    FIRST_NIGHT_NEXT_BUTTON : "firstNightNextButton",
    FIRST_NIGHT_CHAMELEON_BUTTON : "firstNightChameleonButton",
    FIRST_NIGHT_DIRECTOR_BUTTON : "firstNightDirectorButton",
    FIRST_NIGHT_KILLERS_MEETING_BUTTON : "firstNightKillersMeetingButton",
    FIRST_NIGHT_FORECASTER : "firstNightForecaster",
    FIRST_NIGHT_FORECASTER_BUTTON : "firstNightForecasterButton",
    FIRST_NIGHT_HALFBRO : "firstNightHalfbro",
    FIRST_NIGHT_KILLIST : "killist",
    FIRST_NIGHT_HALFBRO_BUTTON : "firstNightHalfbroButton",
    CHAMELEON_SELECT : "chameleonSelect",
    DIRECTOR_SELECT : "directorSelect",
    FORECASTER_INPUT : "forecasterInput",
    HANG_PLAYER_CLASS : "hanging",
    HANG_PLAYER_IMG : "hangPlayerImg",
    HANG_PLAYER_BUTTON : "hangPlayer",
    DAY_OVERLAY : "dayOverlay",
    HUNG_LOVER_NAME : "hungLoverName",
    DAY_NEXT_BUTTON : "dayNextButton",
    NIGHT_OVERLAY : "nightOverlay",
    NIGHT_EVENT : "nightEvent",
    NE_MESSAGE : "neMessage",
    NE_SELECT : "neSelect",
    NE_SELECT2 : "neSelect2",
    NE_BUTTON : "neButton",
    NIGHT_NEXT_BUTTON : "nightNextButton",
    MORNING_OVERLAY : "morningOverlay",
    MORNING_MESSAGE : "morningMessage",
    MORNING_NEXT_BUTTON : "morningNextButton",
    GAME_END_MORNING : "gameEndM",
    GAME_END_DAY : "gameEndD",
    BOX : "box",
    NAME: "name",
    DUMMY : ""
};
