export const Html = {
    BASKET : "basket",
    CHANGE_GAME_BUTTON : "changeGameButton", 
    GAME_CHANGE_MODAL : "modalGameChange", //div
    SELECT_GAME : "selectGame", //select
    SELECT_GAME_BUTTON : "selectGameButton",
    QUIT_SELECT_GAME_BUTTON : "quitSelectGameButton",
    QUIT_ADD_PLAYER_BUTTON : "quitAddPlayerButton",
    GAME_NAME_DIV : "gameName",
    //player buttons
    MINUS_1_BUTTON : "minus1",
    DOWN_BUTTON : "down",
    UP_BUTTON : "up",
    DROP_IMG_CLASS : "dropImg",
    DROP_NUM_INPUT : "dropNum",
    MINUS_DROP_NUM_BUTTON : "minusM",
    PLAY_BUTTON : "game1",
    TURN_BUTTON : "counting",
    POINT_CLASS: "point",
    ROLE_ICON_CLASS: "role",
    NEXT_BUTTON : "start",
    SHOW_PLAYER_CLASS : "showPlayer",
    CHOOSE_ROLES_OVERLAY : "chooseRolesOverlay",
    CHOOSE_ROLES : "chooseRoles",
    ACTIVE_ROLES : "activeRoles",
    PASSIVE_ROLES : "passiveRoles",
    ROLE_ICON_CHOICE_CLASS : "roleChoice",
    ROLES_SELECTED_BUTTON : "rolesSelectedButton",
    ROLE_ICON : "roleIcon",
    PLAYER_OP_CLASS : "playerOp",
    SHOW_ROLE_WINDOW : "showRoleOverlay",
    SHOW_ROLE_CONTENT: "showRoleContent",
    SHOW_ROLE_IMG : "showRoleImg",
    SHOW_ROLE_NAME : "showRoleName",
    SHOW_ROLE_DESC : "showRoleDesc",
    SHOW_ROLE_ROLE : "showRoleRole",
    SHOW_ROLE_CLOSE_BUTTON : "showRoleCloseButton",
    SHO_ROLE_ICON : "showPlayerImg",

    DUMMY : ""
};